force-app/main/default/objects/Knowledge_Base_Document__c/Knowledge_Base_Document__c.object-meta.xml
<CustomObject>
    <description>Object to store information about the knowledge base for the bot.</description>
    <label>Knowledge Base Document</label>
    <nameField>
        <label>Knowledge Base Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knowledge Base Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge_Document_Syncing__c/Knowledge_Document_Syncing__c.object-meta.xml
<CustomObject>
    <label>Knowledge Document Syncing</label>
    <nameField>
        <label>Knowledge Document Syncing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knowledge Documents Syncing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge_Document_Syncing__c/fields/IsSynced__c.field-meta.xml
<CustomField>
    <fullName>IsSynced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSynced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DeleteRelatedFileTest.cls
@isTest
public class DeleteRelatedFileTest {
    
  @isTest
	static void testDeleteRelatedFiles() {
           Knowledge_Document_Syncing__c kdSync = new Knowledge_Document_Syncing__c(Name='Knowledge Document Sync Check', IsSynced__c=false);
        insert kdSync;   
   Knowledge_Base_Document__c testDoc = new Knowledge_Base_Document__c(Name = 'Test Document');
    insert testDoc;

    ContentVersion contentVersion = new ContentVersion(
        Title = 'Test File',
        VersionData = Blob.valueOf('Test Content'),
        PathOnClient = 'TestFile.pdf'
    );
    insert contentVersion;
    
    ContentDocumentLink contentLink = new ContentDocumentLink(
        LinkedEntityId = testDoc.Id,
        ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id].ContentDocumentId
    );
    insert contentLink;

    Test.startTest();
    delete testDoc;
    Test.stopTest();

    List<ContentDocument> remainingDocuments = [
        SELECT Id FROM ContentDocument WHERE Id = :contentLink.ContentDocumentId
    ];
    System.assertEquals(0, remainingDocuments.size());
}

}